### ISSUE TITLE
Add iframe field to action modal

### ISSUE THREAD

**Issue by fouedmoussi** [metrixinfo/nova-iframe#1]
This would be very useful to add iframe field as a preview of an HTML web page in Laravel Nova action modal. 

<img width="1440" alt="Screen Shot 2019-07-17 at 09 51 18" src="https://user-images.githubusercontent.com/15153313/61362000-5d387100-a879-11e9-9a1b-336d725b9fe4.png">
<img width="1440" alt="Screen Shot 2019-07-17 at 09 55 18" src="https://user-images.githubusercontent.com/15153313/61362001-5d387100-a879-11e9-9766-ed77f53cfbb1.png">

**Comment by metrixinfo** [comment]
Previews like that are now available in Nova 4.
